services:
  mysql:
    image: 'mysql:9.5.0'
    environment:
      - 'MYSQL_DATABASE=career_plan'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
  mongo:
    image: mongo:8.2.2-rc0-noble
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bigchuang
#  mongo-express:
#    image: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_BASICAUTH: true
  redis:
    image: redis/redis-stack:7.4.0-v8
    ports:
      - "6379:6379"
      - "8002:8002"
    # 定义所有服务
    # RabbitMQ 服务
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # 5672: AMQP 协议端口，用于应用程序连接 RabbitMQ
      - "5672:5672"
      # 15672: RabbitMQ 管理界面的 Web 端口
      - "15672:15672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
    # 重启策略
    # unless-stopped: 除非手动停止，否则容器总是在退出后自动重启
#    restart: unless-stopped
#volumes:
#  rabbitmq_data:
#    driver: local
  neo4j:
    image: neo4j:ubi9
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=\[\"apoc\"\]
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always