apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bc-backend-ingress
  namespace: bc-backend
spec:
  rules:
    # 不需要指定 host，它会默认匹配 K3s 机器的 IP
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bc-backend
                port:
                  number: 8080